### ISSUE TITLE
create a utility to benchmark vs ndarray, NumPy

### ISSUE THREAD

**Issue by haydnv** [haydnv/ha-ndarray#18]

**Comment by peterlionelnewman** [comment]
[ha_ndarray_comparison.zip](https://github.com/haydnv/ha-ndarray/files/13042210/ha_ndarray_comparison.zip)
Saw your crate and its looked interesting. started snooping around and saw this help wanted.
Do you want something like this? (pyo3 + built with maturin and graphed with matplotlib) (orange = ndarray, magenta = numpy)
<img width="1989" alt="Screenshot 2023-10-19 at 23 16 09" src="https://github.com/haydnv/ha-ndarray/assets/35971555/1119a190-ed2a-44ae-bc9e-d93c4d305ede">

**Comment by haydnv** [comment]
@peterlionelnewman yes this is great! You can see some usage examples to follow in the [examples](https://github.com/haydnv/ha-ndarray/tree/main/examples) directory. Do you need any more guidance/resources in order to connect the benchmark script to the library?
